### ISSUE TITLE
not working well with mongoid

### ISSUE THREAD

**Issue by jamesrxian** [Macrow/rails_kindeditor#13]
I'm working on rails(3.2.6),  mongoid(3.0.5), carrierwave(0.6.2), carrierwave-mongoid(0.1.0).
I followed your guidance after installing rails_kineditor, when I start service using thin(1.4.1), the following error MSG appears:
`undefined method 'collection_name=' for Kindeditor::Asset:Class`.
Then I checked there are several model include Kindeditor::Asset in my apps, 
Why would I see such MSG?
Thx!
